# Generated by Django 5.1.5 on 2025-05-09 06:49

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_recommendationcategory_recommendation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="category",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("stress_relief", "Stress Relief"),
                    ("sleep", "Sleep"),
                    ("focus", "Focus"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.RenameField(
            model_name="userrecommendation",
            old_name="saved_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="profile",
            name="notification_preferences",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_self_care_hours",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(blank=True, default="UTC", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recommendation",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userrecommendation",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userrecommendation",
            name="liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userrecommendation",
            name="saved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="userrecommendation",
            unique_together={("user", "recommendation")},
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.ManyToManyField(blank=True, to="accounts.interest"),
        ),
        migrations.DeleteModel(
            name="RecommendationCategory",
        ),
    ]
