# Generated by Django 5.1.5 on 2025-05-10 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_alter_planneritem_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrecommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="planneritem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined", models.DateField(auto_now_add=True)),
                (
                    "profile_pic",
                    models.ImageField(default="default.jpg", upload_to="profile_pics/"),
                ),
                ("status", models.CharField(default="Active", max_length=20)),
                (
                    "timezone",
                    models.CharField(
                        blank=True, default="UTC", max_length=50, null=True
                    ),
                ),
                (
                    "preferred_self_care_hours",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notification_preferences", models.TextField(blank=True, null=True)),
                (
                    "interests",
                    models.ManyToManyField(blank=True, to="accounts.interest"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
