# Generated by Django 5.1.5 on 2025-05-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_alter_userrecommendation_user_alter_planneritem_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
