# Generated by Django 5.1.5 on 2025-05-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
    ]
